version: '3.3'
services:
  glpi:
    image: my/glpi
    environment:
      VIRTUAL_HOST: your.domain.name
      LETSENCRYPT_HOST: your.domain.name
      LETSENCRYPT_EMAIL: your.email.address
    volumes:
      - type: volume
        source: glpiconfig
        target: /var/www/html/config
    networks:
      - webnet
      - glpidb
  db:
    image: my/mariadb:10.2.9
    environment:
      MYSQL_ROOT_PASSWORD: "admin*"
      MYSQL_DATABASE: glpi
    volumes:
      - type: volume
        source: glpidbvolume
        target: /var/lib/mysql
    networks:
      - glpidb
networks:
  webnet:
    external: true
  glpidb:
volumes:
  glpiconfig:
  glpidbvolume: