
version: '3.3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: volume
        source: nginxconf
        target: /etc/nginx/conf.d
      - type: volume
        source: nginxvhost
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginxhtml
        target: /usr/share/nginx/html
      - "./certs:/etc/nginx/certs:ro"
    networks:
      - webnet
    labels:
     com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy:

  dockergen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    depends_on:
      - nginx
    volumes:
      - type: volume
        source: nginxconf
        target: /etc/nginx/conf.d
      - type: volume
        source: nginxvhost
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginxhtml
        target: /usr/share/nginx/html
      - "./certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl"
    networks:
      - webnet
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen:

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
      - nginx
    volumes:
      - type: volume
        source: nginxconf
        target: /etc/nginx/conf.d
      - type: volume
        source: nginxvhost
        target: /etc/nginx/vhost.d
      - type: volume
        source: nginxhtml
        target: /usr/share/nginx/html
      - "./certs:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

networks:
  webnet:
    external: true

volumes:
  nginxconf:
  nginxvhost:
  nginxhtml:
